type Movie {
  id: Int!
  title: String!
  original_title: String!
  poster_path: String!
  overview: String!
  genres: [MovieGenre!]!
}

input MovieFilter {
  year: Int
  genres: [Int!]
}

enum MovieSort {
  POPULARITY_DESC
  POPULARITY_ASC
  RELEASE_DATE_ASC
  RELEASE_DATE_DESC
  REVENUE_ASC
  REVENUE_DESC
  PRIMARY_RELEASE_DATE_ASC
  PRIMARY_RELEASE_DATE_DESC
  ORIGINAL_TITLE_ASC
  ORIGINAL_TITLE_DESC
  VOTE_AVERAGE_ASC
  VOTE_AVERAGE_DESC
  VOTE_COUNT_ASC
  VOTE_COUNT_DESC
}

type MovieGenre {
  id: Int!
  name: String!
}

type Query {
  movies(sort: MovieSort, filter: MovieFilter): [Movie!]!
  movie(id: Int!): Movie!
  genres: [MovieGenre!]!
}
